### ISSUE TITLE
setup: upgrade `snakemake` version

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-commons#295]
Currently, we have `snakemake>=6.5.3,<6.6.0` installed.

https://github.com/reanahub/reana-commons/blob/3ca6146ddb7647bc21addb081ad3b352b67e290a/setup.py#L29

[Latest version](https://pypi.org/project/snakemake/) at the current date is `6.8.0`

**TODO:**
- [x] Upgrade to latest snakemake version. https://github.com/reanahub/reana-commons/pull/297
- [x] Check that all examples run fine, including `r-d-cms-h4l`.
- [x] Release a new `reana-commons` version with `reana-dev git-create-release-commit -c .`.
- [x] Run `reana-dev git-upgrade-shared-modules -c . --use-latest-known-tag` and `pip-compile` in `r-w-e-snakemake` to update `requirements.txt`.
